In [1]:
import pickle 
import pandas as pd
df=pd.read_pickle('pandasFormat.pkl')

In [2]:
print(len(df.columns))
df.columns

28

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.dates', 'info.gender', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       'info.player_of_match', 'info.teams', 'info.toss.decision',
       'info.toss.winner', 'info.umpires', 'info.venue', 'match_id',
       'info.city', 'info.outcome.by.runs', 'info.match_type_number',
       'info.neutral_venue', 'info.outcome.method', 'info.outcome.result',
       'info.outcome.eliminator', 'info.supersubs.New Zealand',
       'info.supersubs.South Africa', 'info.bowl_out',
       'info.outcome.bowl_out'],
      dtype='object')

In [3]:
df

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,[2017-02-17],male,T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,[2017-02-19],male,T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,[2017-02-22],male,T20,NaN,Australia,20,...,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,[2016-09-05],male,T20,NaN,Hong Kong,20,...,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,[2016-06-18],male,T20,NaN,Zimbabwe,20,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-05,2,[2016-03-04],male,T20,6.0,Pakistan,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2016-03-08,1,[2016-03-06],male,T20,8.0,India,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,[2016-02-03],male,T20,NaN,Netherlands,20,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-09-12,1,[2016-09-06],male,T20,NaN,Australia,20,...,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-09-12,1,[2016-09-09],male,T20,4.0,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1432 entries, 0 to 0
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   innings                      1432 non-null   object
 1   meta.data_version            1432 non-null   float64
 2   meta.created                 1432 non-null   object
 3   meta.revision                1432 non-null   int64
 4   info.dates                   1432 non-null   object
 5   info.gender                  1432 non-null   object
 6   info.match_type              1432 non-null   object
 7   info.outcome.by.wickets      662 non-null    float64
 8   info.outcome.winner          1386 non-null   object
 9   info.overs                   1432 non-null   int64
 10  info.player_of_match         1269 non-null   object
 11  info.teams                   1432 non-null   object
 12  info.toss.decision           1432 non-null   object
 13  info.toss.winner             1432 non-null   object
 14  info.umpires                 1410 non-null   object
 15  info.venue                   1432 non-null   object
 16  match_id                     1432 non-null   int64
 17  info.city                    1240 non-null   object
 18  info.outcome.by.runs         724 non-null    float64
 19  info.match_type_number       699 non-null    float64
 20  info.neutral_venue           328 non-null    float64
 21  info.outcome.method          51 non-null     object
 22  info.outcome.result          46 non-null     object
 23  info.outcome.eliminator      16 non-null     object
 24  info.supersubs.New Zealand   1 non-null      object
 25  info.supersubs.South Africa  1 non-null      object
 26  info.bowl_out                2 non-null      object
 27  info.outcome.bowl_out        2 non-null      object
dtypes: float64(5), int64(3), object(20)
memory usage: 324.4+ KB

In [5]:
df1=df.copy()

###  Below 1432 there is only one column that is necessary, "8-'info.outcome.winner'-1386 non-null-object ", so drop rest columns

In [6]:
df1 = df1.dropna(axis=1, thresh=1386)

In [7]:
df1.columns

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.dates', 'info.gender', 'info.match_type', 'info.outcome.winner',
       'info.overs', 'info.teams', 'info.toss.decision', 'info.toss.winner',
       'info.umpires', 'info.venue', 'match_id'],
      dtype='object')

In [8]:
df1

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,[2017-02-17],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,[2017-02-19],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,[2017-02-22],male,T20,Australia,20,"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,[2016-09-05],male,T20,Hong Kong,20,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,[2016-06-18],male,T20,Zimbabwe,20,"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-05,2,[2016-03-04],male,T20,Pakistan,20,"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,1428
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2016-03-08,1,[2016-03-06],male,T20,India,20,"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,1429
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,[2016-02-03],male,T20,Netherlands,20,"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,1430
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-09-12,1,[2016-09-06],male,T20,Australia,20,"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,1431
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-09-12,1,[2016-09-09],male,T20,Australia,20,"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,1432

### Drop other unnecessary columns

In [9]:
df1=df1.drop(columns=['meta.data_version','meta.created','meta.revision','info.umpires','match_id'])

In [10]:
df1

,innings,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.teams,info.toss.decision,info.toss.winner,info.venue
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,Melbourne Cricket Ground
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,"Simonds Stadium, South Geelong"
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],male,T20,Australia,20,"[Australia, Sri Lanka]",field,Sri Lanka,Adelaide Oval
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],male,T20,Hong Kong,20,"[Ireland, Hong Kong]",bat,Hong Kong,"Bready Cricket Club, Magheramason"
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],male,T20,Zimbabwe,20,"[Zimbabwe, India]",field,India,Harare Sports Club
...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-03-04],male,T20,Pakistan,20,"[Pakistan, Sri Lanka]",field,Pakistan,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2016-03-06],male,T20,India,20,"[Bangladesh, India]",field,India,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",[2016-02-03],male,T20,Netherlands,20,"[United Arab Emirates, Netherlands]",field,United Arab Emirates,ICC Academy
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2016-09-06],male,T20,Australia,20,"[Sri Lanka, Australia]",field,Sri Lanka,Pallekele International Cricket Stadium
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-09-09],male,T20,Australia,20,"[Sri Lanka, Australia]",bat,Sri Lanka,R Premadasa Stadium

### Keep only those rows which is
###  'info.gender'=male    'info.match_type' = T20,      'info.overs'=20 ,

In [11]:
df1=df1[(df1['info.gender']=='male') & (df1['info.match_type']=='T20') & (df1['info.overs']==20 )]

In [12]:
df1

,innings,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.teams,info.toss.decision,info.toss.winner,info.venue
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,Melbourne Cricket Ground
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],male,T20,Sri Lanka,20,"[Australia, Sri Lanka]",field,Sri Lanka,"Simonds Stadium, South Geelong"
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],male,T20,Australia,20,"[Australia, Sri Lanka]",field,Sri Lanka,Adelaide Oval
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],male,T20,Hong Kong,20,"[Ireland, Hong Kong]",bat,Hong Kong,"Bready Cricket Club, Magheramason"
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],male,T20,Zimbabwe,20,"[Zimbabwe, India]",field,India,Harare Sports Club
...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-03-04],male,T20,Pakistan,20,"[Pakistan, Sri Lanka]",field,Pakistan,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2016-03-06],male,T20,India,20,"[Bangladesh, India]",field,India,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",[2016-02-03],male,T20,Netherlands,20,"[United Arab Emirates, Netherlands]",field,United Arab Emirates,ICC Academy
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2016-09-06],male,T20,Australia,20,"[Sri Lanka, Australia]",field,Sri Lanka,Pallekele International Cricket Stadium
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-09-09],male,T20,Australia,20,"[Sri Lanka, Australia]",bat,Sri Lanka,R Premadasa Stadium

###  No. of rows reduced from 1432 to 963, now delete those 3 columns because it is constant

In [13]:
df1=df1.drop(columns=['info.gender','info.match_type','info.overs'])

In [14]:
df1=df1.drop(columns=['info.dates'])

In [15]:
df1

,innings,info.outcome.winner,info.teams,info.toss.decision,info.toss.winner,info.venue
0,"[{'1st innings': {'team': 'Australia', 'delive...",Sri Lanka,"[Australia, Sri Lanka]",field,Sri Lanka,Melbourne Cricket Ground
0,"[{'1st innings': {'team': 'Australia', 'delive...",Sri Lanka,"[Australia, Sri Lanka]",field,Sri Lanka,"Simonds Stadium, South Geelong"
0,"[{'1st innings': {'team': 'Australia', 'delive...",Australia,"[Australia, Sri Lanka]",field,Sri Lanka,Adelaide Oval
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",Hong Kong,"[Ireland, Hong Kong]",bat,Hong Kong,"Bready Cricket Club, Magheramason"
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Zimbabwe,"[Zimbabwe, India]",field,India,Harare Sports Club
...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",Pakistan,"[Pakistan, Sri Lanka]",field,Pakistan,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",India,"[Bangladesh, India]",field,India,Shere Bangla National Stadium
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",Netherlands,"[United Arab Emirates, Netherlands]",field,United Arab Emirates,ICC Academy
0,"[{'1st innings': {'team': 'Australia', 'delive...",Australia,"[Sri Lanka, Australia]",field,Sri Lanka,Pallekele International Cricket Stadium
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",Australia,"[Sri Lanka, Australia]",bat,Sri Lanka,R Premadasa Stadium

### Correct the indexing if its unordered, or zero for all rows

In [16]:
df1=df1.reset_index(drop=True)
df1

,innings,info.outcome.winner,info.teams,info.toss.decision,info.toss.winner,info.venue
0,"[{'1st innings': {'team': 'Australia', 'delive...",Sri Lanka,"[Australia, Sri Lanka]",field,Sri Lanka,Melbourne Cricket Ground
1,"[{'1st innings': {'team': 'Australia', 'delive...",Sri Lanka,"[Australia, Sri Lanka]",field,Sri Lanka,"Simonds Stadium, South Geelong"
2,"[{'1st innings': {'team': 'Australia', 'delive...",Australia,"[Australia, Sri Lanka]",field,Sri Lanka,Adelaide Oval
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",Hong Kong,"[Ireland, Hong Kong]",bat,Hong Kong,"Bready Cricket Club, Magheramason"
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",Zimbabwe,"[Zimbabwe, India]",field,India,Harare Sports Club
...,...,...,...,...,...,...
958,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",Pakistan,"[Pakistan, Sri Lanka]",field,Pakistan,Shere Bangla National Stadium
959,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",India,"[Bangladesh, India]",field,India,Shere Bangla National Stadium
960,"[{'1st innings': {'team': 'Netherlands', 'deli...",Netherlands,"[United Arab Emirates, Netherlands]",field,United Arab Emirates,ICC Academy
961,"[{'1st innings': {'team': 'Australia', 'delive...",Australia,"[Sri Lanka, Australia]",field,Sri Lanka,Pallekele International Cricket Stadium
962,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",Australia,"[Sri Lanka, Australia]",bat,Sri Lanka,R Premadasa Stadium

### Upto now we have handled missing values, and we have kept only the required rows and columns and dropped rest.
### Now we will deal with 1st column 'innings'

In [17]:
df1.iloc[0,0]

[{'1st innings': {'team': 'Australia',
   'deliveries': [{0.1: {'batsman': 'AJ Finch',
      'bowler': 'SL Malinga',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.2: {'batsman': 'AJ Finch',
      'bowler': 'SL Malinga',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.3: {'batsman': 'AJ Finch',
      'bowler': 'SL Malinga',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {0.4: {'batsman': 'M Klinger',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {0.5: {'batsman': 'M Klinger',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.6: {'batsman': 'M Klinger',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {1.1: {'batsman': 'M Klinger',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.2: {'batsman': 'M Klinger',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {1.3: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.4: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.5: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {1.6: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {2.1: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {2.2: {'batsman': 'AJ Finch',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {2.3: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.4: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.5: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {2.6: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.1: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.2: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.3: {'batsman': 'M Klinger',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.4: {'batsman': 'AJ Finch',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.5: {'batsman': 'M Klinger',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {3.6: {'batsman': 'M Klinger',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.1: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {4.2: {'batsman': 'AJ Finch',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {4.3: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {4.4: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {4.5: {'batsman': 'M Klinger',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.6: {'batsman': 'AJ Finch',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.1: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.2: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'extras': {'wides': 1},
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {5.3: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.4: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.5: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.6: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.7: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.1: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.2: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.3: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.4: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.5: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.6: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {7.1: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.2: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {7.3: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {7.4: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'extras': {'byes': 1},
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {7.5: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {7.6: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.1: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.2: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {8.3: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.4: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.5: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.6: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {9.1: {'batsman': 'M Klinger',
      'bowler': 'S Prasanna',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {9.2: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.3: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.4: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {9.5: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {9.6: {'batsman': 'AJ Finch',
      'bowler': 'S Prasanna',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.1: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.2: {'batsman': 'AJ Finch',
      'bowler': 'PADLR Sandakan',
      'extras': {'legbyes': 1},
      'non_striker': 'M Klinger',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {10.3: {'batsman': 'M Klinger',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['SL Malinga'],
       'kind': 'caught',
       'player_out': 'M Klinger'}}},
    {10.4: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {10.5: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.6: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'AJ Finch',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {11.1: {'batsman': 'AJ Finch',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'TM Head',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {11.2: {'batsman': 'AJ Finch',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'TM Head',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {11.3: {'batsman': 'AJ Finch',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['SL Malinga'],
       'kind': 'caught',
       'player_out': 'AJ Finch'}}},
    {11.4: {'batsman': 'TM Head',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.5: {'batsman': 'MC Henriques',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.6: {'batsman': 'TM Head',
      'bowler': 'DAS Gunaratne',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.1: {'batsman': 'TM Head',
      'bowler': 'S Prasanna',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.2: {'batsman': 'TM Head',
      'bowler': 'S Prasanna',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.3: {'batsman': 'MC Henriques',
      'bowler': 'S Prasanna',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.4: {'batsman': 'TM Head',
      'bowler': 'S Prasanna',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.5: {'batsman': 'TM Head',
      'bowler': 'S Prasanna',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.6: {'batsman': 'MC Henriques',
      'bowler': 'S Prasanna',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.1: {'batsman': 'MC Henriques',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {13.2: {'batsman': 'MC Henriques',
      'bowler': 'SL Malinga',
      'extras': {'wides': 1},
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {13.3: {'batsman': 'MC Henriques',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.4: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {13.5: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.6: {'batsman': 'MC Henriques',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.7: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.1: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.2: {'batsman': 'MC Henriques',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'TM Head',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {14.3: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.4: {'batsman': 'MC Henriques',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'TM Head',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {14.5: {'batsman': 'MC Henriques',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'TM Head',
      'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
    {14.6: {'batsman': 'TM Head',
      'bowler': 'PADLR Sandakan',
      'non_striker': 'MC Henriques',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {15.1: {'batsman': 'MC Henriques',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['CK Kapugedera'],
       'kind': 'caught',
       'player_out': 'MC Henriques'}}},
    {15.2: {'batsman': 'TM Head',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {15.3: {'batsman': 'AJ Turner',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'TM Head',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {15.4: {'batsman': 'AJ Turner',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {15.5: {'batsman': 'TM Head',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {15.6: {'batsman': 'TM Head',
      'bowler': 'JRMVB Sanjaya',
      'extras': {'wides': 1},
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {15.7: {'batsman': 'TM Head',
      'bowler': 'JRMVB Sanjaya',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {16.1: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {16.2: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {16.3: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.4: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.5: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.6: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.1: {'batsman': 'TM Head',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.2: {'batsman': 'AJ Turner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TM Head',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {17.3: {'batsman': 'AJ Turner',
      'bowler': 'KMDN Kulasekara',
      'extras': {'noballs': 1},
      'non_striker': 'TM Head',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {17.4: {'batsman': 'AJ Turner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.5: {'batsman': 'TM Head',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.6: {'batsman': 'AJ Turner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.7: {'batsman': 'TM Head',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {18.1: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {18.2: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'TM Head',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {18.3: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {18.4: {'batsman': 'TM Head',
      'bowler': 'SL Malinga',
      'non_striker': 'AJ Turner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['S Prasanna'],
       'kind': 'caught',
       'player_out': 'TM Head'}}},
    {18.5: {'batsman': 'AJ Turner',
      'bowler': 'SL Malinga',
      'non_striker': 'JP Faulkner',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['S Prasanna'],
       'kind': 'caught',
       'player_out': 'AJ Turner'}}},
    {18.6: {'batsman': 'JP Faulkner',
      'bowler': 'SL Malinga',
      'non_striker': 'TD Paine',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {19.1: {'batsman': 'JP Faulkner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TD Paine',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {19.2: {'batsman': 'JP Faulkner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TD Paine',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {19.3: {'batsman': 'JP Faulkner',
      'bowler': 'KMDN Kulasekara',
      'non_striker': 'TD Paine',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {19.4: {'batsman': 'JP Faulkner',
      'bowler': 'KMDN Kulasekara',
      'extras': {'wides': 1},

### We observed that each element in 1st column contains ball-by-ball info of both the inning, and it is very compact, nested dictionaries and lists


### Final model input:  
#### BattingTeam, BowlingTeam, Venue, Inning, Overs(more than 10), Score, Wickets, Runs in last 5 overs, Target(if 2nd inning)
### Output : Final score after 20 overs

In [18]:
df1.iloc[3,0][1]['2nd innings']['deliveries']

[{0.1: {'batsman': 'WTS Porterfield',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {0.2: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.4: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.5: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {0.6: {'batsman': 'WTS Porterfield',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.1: {'batsman': 'WTS Porterfield',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'WTS Porterfield',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.3: {'batsman': 'WTS Porterfield',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Tanwir Afzal'],
    'kind': 'caught',
    'player_out': 'WTS Porterfield'}}},
 {1.4: {'batsman': 'SP Terry',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.5: {'batsman': 'SP Terry',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.6: {'batsman': 'SP Terry',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.1: {'batsman': 'SP Terry',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.2: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'SP Terry',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.3: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'SP Terry',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.4: {'batsman': 'SP Terry',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {2.5: {'batsman': 'SP Terry',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'SP Terry'}}},
 {2.6: {'batsman': 'JNK Shannon',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'DA Rankin',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.2: {'batsman': 'DA Rankin',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.3: {'batsman': 'DA Rankin',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {3.4: {'batsman': 'DA Rankin',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.5: {'batsman': 'DA Rankin',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.6: {'batsman': 'JNK Shannon',
   'bowler': 'Nadeem Ahmed',
   'extras': {'wides': 1},
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {3.7: {'batsman': 'JNK Shannon',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'DA Rankin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.1: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.2: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {4.3: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.4: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.5: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.6: {'batsman': 'DA Rankin',
   'bowler': 'Tanwir Afzal',
   'non_striker': 'JNK Shannon',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'DA Rankin'}}},
 {5.1: {'batsman': 'JNK Shannon',
   'bowler': 'Aizaz Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.2: {'batsman': 'JNK Shannon',
   'bowler': 'Aizaz Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Nadeem Ahmed'],
    'kind': 'caught',
    'player_out': 'JNK Shannon'}}},
 {5.3: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.4: {'batsman': "KJ O'Brien",
   'bowler': 'Aizaz Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.5: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.6: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.1: {'batsman': "KJ O'Brien",
   'bowler': 'Tanwir Afzal',
   'extras': {'legbyes': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {6.2: {'batsman': 'GJ Thompson',
   'bowler': 'Tanwir Afzal',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': "KJ O'Brien",
   'bowler': 'Tanwir Afzal',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.4: {'batsman': "KJ O'Brien",
   'bowler': 'Tanwir Afzal',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'GJ Thompson',
   'bowler': 'Tanwir Afzal',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': "KJ O'Brien",
   'bowler': 'Tanwir Afzal',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.1: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Nawaz',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.2: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Nawaz',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Nawaz',
   'extras': {'noballs': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 4, 'extras': 1, 'total': 5}}},
 {7.4: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Nawaz',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.5: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Nawaz',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.6: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Nawaz',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.7: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Nawaz',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {8.1: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'extras': {'wides': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {8.2: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {8.3: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.5: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.7: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': "KJ O'Brien",
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.2: {'batsman': "KJ O'Brien",
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.3: {'batsman': "KJ O'Brien",
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.4: {'batsman': 'GJ Thompson',
   'bowler': 'Nadeem Ahmed',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {9.5: {'batsman': 'GJ Thompson',
   'bowler': 'Nadeem Ahmed',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.6: {'batsman': "KJ O'Brien",
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.1: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {10.2: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.3: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.4: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.5: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.6: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.1: {'batsman': "KJ O'Brien",
   'bowler': 'Tanveer Ahmed',
   'extras': {'wides': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {11.2: {'batsman': "KJ O'Brien",
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.3: {'batsman': "KJ O'Brien",
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.4: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {11.5: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.6: {'batsman': "KJ O'Brien",
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.7: {'batsman': "KJ O'Brien",
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {12.1: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.2: {'batsman': "KJ O'Brien",
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Tanveer Ahmed'],
    'kind': 'caught',
    'player_out': "KJ O'Brien"}}},
 {12.3: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.4: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'extras': {'byes': 4},
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 4, 'total': 4}}},
 {12.5: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.6: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.1: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {13.2: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {13.3: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {13.4: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.5: {'batsman': 'GJ Thompson',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'AR McBrine',
   'bowler': 'Tanveer Ahmed',
   'extras': {'legbyes': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {14.1: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.2: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {14.3: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {14.4: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.5: {'batsman': 'AR McBrine',
   'bowler': 'Ehsan Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.6: {'batsman': 'GJ Thompson',
   'bowler': 'Ehsan Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.1: {'batsman': 'GJ Thompson',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.2: {'batsman': 'AR McBrine',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['C Carter'],
    'kind': 'stumped',
    'player_out': 'AR McBrine'}}},
 {15.3: {'batsman': 'L Tucker',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.4: {'batsman': 'GJ Thompson',
   'bowler': 'Nadeem Ahmed',
   'extras': {'legbyes': 1},
   'non_striker': 'L Tucker',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.5: {'batsman': 'L Tucker',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.6: {'batsman': 'L Tucker',
   'bowler': 'Nadeem Ahmed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.1: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': 'L Tucker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.2: {'batsman': 'L Tucker',
   'bowler': 'Aizaz Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.3: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': 'L Tucker',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.4: {'batsman': 'GJ Thompson',
   'bowler': 'Aizaz Khan',
   'non_striker': 'L Tucker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Nadeem Ahmed'],
    'kind': 'caught',
    'player_out': 'GJ Thompson'}}},
 {16.5: {'batsman': 'L Tucker',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.6: {'batsman': 'L Tucker',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'L Tucker',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.2: {'batsman': 'J Mulder',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'L Tucker',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.3: {'batsman': 'J Mulder',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'L Tucker',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.4: {'batsman': 'L Tucker',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.5: {'batsman': 'L Tucker',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'L Tucker'}}},
 {17.6: {'batsman': 'J Little',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'J Mulder',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.1: {'batsman': 'J Mulder',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Little',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.2: {'batsman': 'J Mulder',
   'bowler': 'Aizaz Khan',
   'extras': {'legbyes': 2},
   'non_striker': 'J Little',
   'runs': {'batsman': 0, 'extras': 2, 'total': 2}}},
 {18.3: {'batsman': 'J Mulder',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Little',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'J Mulder'}}},
 {18.4: {'batsman': 'CA Young',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Little',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.5: {'batsman': 'CA Young',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Little',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.6: {'batsman': 'CA Young',
   'bowler': 'Aizaz Khan',
   'non_striker': 'J Little',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'CA Young',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'J Little',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.2: {'batsman': 'J Little',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'CA Young',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.3: {'batsman': 'J Little',
   'bowler': 'Tanveer Ahmed',
   'non_striker': 'CA Young',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'J Little'}}}]

In [19]:
dataset=[]

for i in range(len(df1)):
    try:
        dataset.append([])

        teams=df1.loc[i]['info.teams']
        toss_winner=df1.loc[i]['info.toss.winner']
        toss_choice=df1.loc[i]['info.toss.decision']
        batting_1st_inning = toss_winner if toss_choice == 'bat' else (set(teams) - set([toss_winner])).pop()
        bowling_1st_inning=(set(teams) - set([batting_1st_inning])).pop()
        # Ist inning
        df2=pd.DataFrame()
        score=0
        wickets=0
        deliveries=df1.iloc[i,0][0]['1st innings']['deliveries']
        for j in range(len(deliveries)):
            over=list(deliveries[j].keys())[0]
            run=deliveries[j][over]['runs']['total']
            score+=run
            wickets+=1 if 'wicket' in deliveries[j][over] else 0
            dic=pd.DataFrame({'over':[over],'score':[score],'wickets':[wickets]})
            df2=pd.concat([df2,dic],ignore_index=True)

        df2['batting']=batting_1st_inning
        df2['bowling']=bowling_1st_inning
        df2['inning']=1

        dataset[-1].append(df2)

        # IInd inning
        df2=pd.DataFrame()
        score=0
        wickets=0
        deliveries=df1.iloc[i,0][1]['2nd innings']['deliveries']
        for j in range(len(deliveries)):
            over=list(deliveries[j].keys())[0]
            run=deliveries[j][over]['runs']['total']
            score+=run
            wickets+=1 if 'wicket' in deliveries[j][over] else 0
            dic=pd.DataFrame({'over':[over],'score':[score],'wickets':[wickets]})
            df2=pd.concat([df2,dic],ignore_index=True)

        df2['batting']=bowling_1st_inning
        df2['bowling']=batting_1st_inning  
        df2['inning']=2
        dataset[-1].append(df2)
    except:
        print(i)
        dataset.pop()

65
111
136
211
226
305
431
652
698
817
899

#### In the above matches, there is some different data structure used, thats why its throwing error.
#### Below, we will found that few of them don't have 2nd inning played, We will discard that data.

In [20]:
df1.iloc[65,0]

[{'1st innings': {'team': 'New Zealand',
   'deliveries': [{0.1: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'MJ Guptill'}},
    {0.2: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'MJ Guptill'}},
    {0.3: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'MJ Guptill'}},
    {0.4: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 1, 'total': 1, 'batsman': 0},
      'extras': {'wides': 1},
      'batsman': 'MJ Guptill'}},
    {0.5: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'MJ Guptill',
      'wicket': {'player_out': 'MJ Guptill',
       'fielders': ['CAK Walton'],
       'kind': 'caught'}}},
    {0.6: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'KS Williamson'}},
    {0.7: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {1.1: {'non_striker': 'C Munro',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'KS Williamson'}},
    {1.2: {'non_striker': 'C Munro',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {1.3: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro'}},
    {1.4: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {1.5: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro'}},
    {1.6: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {2.1: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {2.2: {'non_striker': 'KS Williamson',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 6, 'batsman': 6},
      'batsman': 'C Munro'}},
    {2.3: {'non_striker': 'KS Williamson',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'C Munro'}},
    {2.4: {'non_striker': 'KS Williamson',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 6, 'batsman': 6},
      'batsman': 'C Munro'}},
    {2.5: {'non_striker': 'KS Williamson',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'C Munro'}},
    {2.6: {'non_striker': 'C Munro',
      'bowler': 'SS Cottrell',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {3.1: {'non_striker': 'C Munro',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {3.2: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {3.3: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro'}},
    {3.4: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro'}},
    {3.5: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {3.6: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro'}},
    {4.1: {'non_striker': 'C Munro',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {4.2: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 6, 'batsman': 6},
      'batsman': 'C Munro'}},
    {4.3: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {4.4: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {4.5: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 1, 'total': 1, 'batsman': 0},
      'extras': {'wides': 1},
      'batsman': 'C Munro'}},
    {4.6: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {4.7: {'non_striker': 'KS Williamson',
      'bowler': 'CR Brathwaite',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'C Munro'}},
    {5.1: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {5.2: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {5.3: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {5.4: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'C Munro'}},
    {5.5: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'C Munro',
      'wicket': {'player_out': 'C Munro',
       'fielders': ['R Powell'],
       'kind': 'caught'}}},
    {5.6: {'non_striker': 'GD Phillips',
      'bowler': 'KOK Williams',
      'runs': {'extras': 1, 'total': 2, 'batsman': 1},
      'extras': {'noballs': 1},
      'batsman': 'KS Williamson'}},
    {5.7: {'non_striker': 'KS Williamson',
      'bowler': 'KOK Williams',
      'runs': {'extras': 0, 'total': 6, 'batsman': 6},
      'batsman': 'GD Phillips'}},
    {6.1: {'non_striker': 'GD Phillips',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {6.2: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'GD Phillips'}},
    {6.3: {'non_striker': 'GD Phillips',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'KS Williamson'}},
    {6.4: {'non_striker': 'GD Phillips',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'KS Williamson'}},
    {6.5: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'GD Phillips'}},
    {6.6: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'GD Phillips'}},
    {7.1: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'GD Phillips',
      'wicket': {'player_out': 'GD Phillips', 'kind': 'lbw'}}},
    {7.2: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'TC Bruce'}},
    {7.3: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'TC Bruce'}},
    {7.4: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'TC Bruce'}},
    {7.5: {'non_striker': 'KS Williamson',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'TC Bruce'}},
    {7.6: {'non_striker': 'TC Bruce',
      'bowler': 'S Badree',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'KS Williamson'}},
    {8.1: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'TC Bruce'}},
    {8.2: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 2, 'batsman': 2},
      'batsman': 'TC Bruce'}},
    {8.3: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'TC Bruce',
      'wicket': {'player_out': 'TC Bruce',
       'fielders': ['CR Brathwaite'],
       'kind': 'caught'}}},
    {8.4: {'non_striker': 'KS Williamson',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 1, 'batsman': 1},
      'batsman': 'AK Kitchen'}},
    {8.5: {'non_striker': 'AK Kitchen',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 0, 'batsman': 0},
      'batsman': 'KS Williamson'}},
    {8.6: {'non_striker': 'AK Kitchen',
      'bowler': 'AR Nurse',
      'runs': {'extras': 0, 'total': 4, 'batsman': 4},
      'batsman': 'KS Williamson'}}]}}]

In [21]:
len(dataset)

952

In [22]:
df1.loc[10]

innings                [{'1st innings': {'team': 'South Africa', 'del...
info.outcome.winner                                         South Africa
info.teams                                   [New Zealand, South Africa]
info.toss.decision                                                 field
info.toss.winner                                             New Zealand
info.venue                                                     Eden Park
Name: 10, dtype: object

In [25]:
dataset[10][0]

     over  score  wickets       batting      bowling  inning
0     0.1      0        0  South Africa  New Zealand       1
1     0.2      4        0  South Africa  New Zealand       1
2     0.3      4        0  South Africa  New Zealand       1
3     0.4      4        0  South Africa  New Zealand       1
4     0.5      5        0  South Africa  New Zealand       1
..    ...    ...      ...           ...          ...     ...
117  19.2    179        5  South Africa  New Zealand       1
118  19.3    179        5  South Africa  New Zealand       1
119  19.4    181        5  South Africa  New Zealand       1
120  19.5    181        6  South Africa  New Zealand       1
121  19.6    185        6  South Africa  New Zealand       1

[122 rows x 6 columns]

#### We have successfully expanded the first column, now we have only two column left-
#### 'runs in last 5 overs','final_score'  --------- venue and target(if its 2nd inning) will not be doing

In [61]:
for i in range(len(dataset)):
    print(i)
    for j in range(2):    ## j=0 or 1
        dataset[i][j]['Last5oversRuns']=-1
        for k in range(len(dataset[i][j])):
            over=dataset[i][j].loc[k]['over']
            if over>9.6:
                dataset[i][j].iloc[k,-1]=dataset[i][j].iloc[k,1] - dataset[i][j].iloc[k-30,1]
        dataset[i][j]['Final_score']=dataset[i][j].iloc[-1,1]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951

In [64]:
dataset[10][1]

,over,score,wickets,batting,bowling,inning,Last5oversRuns,Final_score
0,0.1,0,0,New Zealand,South Africa,2,-1,107
1,0.2,0,0,New Zealand,South Africa,2,-1,107
2,0.3,0,0,New Zealand,South Africa,2,-1,107
3,0.4,0,0,New Zealand,South Africa,2,-1,107
4,0.5,1,0,New Zealand,South Africa,2,-1,107
...,...,...,...,...,...,...,...,...
86,14.1,106,8,New Zealand,South Africa,2,51,107
87,14.2,106,8,New Zealand,South Africa,2,51,107
88,14.3,106,9,New Zealand,South Africa,2,51,107
89,14.4,107,9,New Zealand,South Africa,2,48,107
90,14.5,107,10,New Zealand,South Africa,2,48,107

#### Now we combine all the dataset into a single pandas dataframe

In [79]:
dataset2=pd.DataFrame()
for i in range(len(dataset)):
    for j in range(2):
        dataset2=pd.concat([dataset2,dataset[i][j]],ignore_index=True)
dataset2

,over,score,wickets,batting,bowling,inning,Last5oversRuns,Final_score
0,0.1,0,0,Australia,Sri Lanka,1,-1,168
1,0.2,0,0,Australia,Sri Lanka,1,-1,168
2,0.3,1,0,Australia,Sri Lanka,1,-1,168
3,0.4,3,0,Australia,Sri Lanka,1,-1,168
4,0.5,3,0,Australia,Sri Lanka,1,-1,168
...,...,...,...,...,...,...,...,...
220053,17.1,121,6,Australia,Sri Lanka,2,18,130
220054,17.2,124,6,Australia,Sri Lanka,2,21,130
220055,17.3,124,6,Australia,Sri Lanka,2,21,130
220056,17.4,124,6,Australia,Sri Lanka,2,21,130
220057,17.5,130,6,Australia,Sri Lanka,2,26,130

#### For training the model, we will choose only those rows after 10 overs, because we can't predict the final score if a match has not been played for 10 overs yet.

In [80]:
dataset2=dataset2[dataset2['Last5oversRuns'] != -1]

In [83]:
dataset2=dataset2.reset_index(drop=True)

In [84]:
dataset2

,over,score,wickets,batting,bowling,inning,Last5oversRuns,Final_score
0,10.1,75,0,Australia,Sri Lanka,1,30,168
1,10.2,76,0,Australia,Sri Lanka,1,31,168
2,10.3,76,1,Australia,Sri Lanka,1,31,168
3,10.4,78,1,Australia,Sri Lanka,1,32,168
4,10.5,78,1,Australia,Sri Lanka,1,31,168
...,...,...,...,...,...,...,...,...
103180,17.1,121,6,Australia,Sri Lanka,2,18,130
103181,17.2,124,6,Australia,Sri Lanka,2,21,130
103182,17.3,124,6,Australia,Sri Lanka,2,21,130
103183,17.4,124,6,Australia,Sri Lanka,2,21,130
103184,17.5,130,6,Australia,Sri Lanka,2,26,130

In [85]:
import pickle
dataset2.to_pickle('Dataset.pkl')